# Generated by Django 5.0 on 2024-01-01 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projeect',
            new_name='Project',
        ),
    ]
